# Tencent Cloud host deployment workflow for Astro

name: Deploy to Tencent Host

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          DEPLOY_SERVER: deployhost
          BLOG_POST250416: ${{ secrets.BLOG_POST250416 }}
          BLOG_POST250502: ${{ secrets.BLOG_POST250502 }}
          BLOG_POST250507: ${{ secrets.BLOG_POST250507 }}
          BLOG_POST250513: ${{ secrets.BLOG_POST250513 }}
          BLOG_POST250519: ${{ secrets.BLOG_POST250519 }}
          BLOG_POST250520: ${{ secrets.BLOG_POST250520 }}
          BLOG_POST250521: ${{ secrets.BLOG_POST250521 }}
          BLOG_POST250522: ${{ secrets.BLOG_POST250522 }}
          BLOG_POST250525: ${{ secrets.BLOG_POST250525 }}
          BLOG_POST250529: ${{ secrets.BLOG_POST250529 }}
          BLOG_POST250604: ${{ secrets.BLOG_POST250604 }}
          BLOG_POST250727: ${{ secrets.BLOG_POST250727 }}
          BLOG_POST250801: ${{ secrets.BLOG_POST250801 }}
          BLOG_POST250806: ${{ secrets.BLOG_POST250806 }}
          BLOG_POST250824: ${{ secrets.BLOG_POST250824 }}
          BLOG_POST250919: ${{ secrets.BLOG_POST250919 }}
          BLOG_POST250924: ${{ secrets.BLOG_POST250924 }}
          BLOG_POST250929: ${{ secrets.BLOG_POST250929 }}
          BLOG_POST251001: ${{ secrets.BLOG_POST251001 }}
          BLOG_POST251004: ${{ secrets.BLOG_POST251004 }}
          BLOG_POST251006: ${{ secrets.BLOG_POST251006 }}
          BLOG_POST251010: ${{ secrets.BLOG_POST251010 }}
          BLOG_POST251026: ${{ secrets.BLOG_POST251026 }}
          BLOG_POST260416: ${{ secrets.BLOG_POST260416 }}
        run: npm run build-host

      - name: Deploy to Host
        uses: easingthemes/ssh-deploy@v4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: "dist/"
          REMOTE_HOST: "150.158.100.135"
          REMOTE_USER: "root"
          TARGET: "/home/webapps/myblog"
